version: "3.2"
services:
  backend:
    image: fastify-gql-api
    container_name: fastify-gql-api

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8080:8080

    restart: on-failure
